version: '3'

services:

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: silviolcf/node:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: silviolcf/mysql:prod
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: silviolcf/nginx:prod
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodenet
    depends_on:
      - app

networks:
  nodenet:
    driver: bridge
